/** This file is auto-generated by Plasmic; please do not edit! */
import { useRouter } from "next/router";
import PlasmicLoader from "@plasmicapp/loader";

const componentsByPath = {
  
    "new-page": {name: "NewPage", projectId: "wvHgHjhMZ7rRNTU5d8DBjC" },
  
};

export default function PlasmicLoaderPage() {
  const router = useRouter();
  const { plasmicLoaderPage } = router.query;
  const {name, projectId} = componentsByPath[plasmicLoaderPage];

  return <PlasmicLoader component={name} projectId={projectId} />;
}

export async function getStaticProps(context) {
  return {
    props: {},
  };
}

export async function getStaticPaths() {
  return {
    paths: [
      
        { params: { plasmicLoaderPage: ["new-page"] } },
      
    ],
    fallback: false,
  };
}
